{
 "title": "Example Migration Utils Dashboard",
 "time": { "from": "2020-10-08T01:00:00.000Z", "to": "2020-10-08T05:00:00.000Z" },
 "panels": [
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "OCFL Object Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(fcrepo_storage_ocfl_object_seconds_bucket[1m])) by (le, operation))",
     "legendFormat": "{{operation}} p99"
    },
    {
     "expr": "rate(fcrepo_storage_ocfl_object_seconds_sum[1m])/rate(fcrepo_storage_ocfl_object_seconds_count[1m])",
     "legendFormat": "{{operation}} avg"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[1m])/rate(jvm_gc_pause_seconds_count[1m])",
     "legendFormat": "{{cause}} avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(jvm_gc_pause_seconds_bucket[1m])) by (le, cause))",
     "legendFormat": "{{cause}} p99"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count[1m])",
     "legendFormat": "{{cause}}"
    }
   ]
  }
 ]
}