global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "migration-utils"
    metrics_path: "/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          alias: "migration-utils"
